### ISSUE TITLE
Intermittent failure in first build spec

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/metalware#309] opened 2018-02-12 15:58 UTC
I believe there is a race condition in one of the specs. Occasionally I get the following error:
```
[root@localhost metalware]# rspec

Randomized with seed 3341
.............................................................................................................................................................Run the com
plete_hook for nodes as if build succeeded?
[yes/no]
FRun the complete_hook for nodes as if build succeeded?
[yes/no]
...............................................................................................................***......................................................
...............................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Metalware::CommandHelpers::ConfigureCommand renders the server config, hosts, and genders files
     # Temporarily skipped with xit
     # ./spec/shared_examples/render_domain_templates.rb:51

  2) Metalware::CommandHelpers::ConfigureCommand when invalid genders file rendered does not render hosts file and gives error
     # Temporarily skipped with xit
     # ./spec/shared_examples/render_domain_templates.rb:130

  3) Metalware::CommandHelpers::ConfigureCommand when invalid server config rendered does not render hosts and genders files and gives error
     # Temporarily skipped with xit
     # ./spec/shared_examples/render_domain_templates.rb:100


Failures:

  1) `metal build` for gender group interrupt handling with mocked highline handles "no" to interrupt prompt
     Failure/Error:
       expect(testnode01_pxelinux).to eq(
         Metalware::Templater.render(
           alces,
           PXELINUX_TEMPLATE,
           nodename: 'testnode01',
           firstboot: false
         )
       )
     
       expected: "NOT_FIRSTBOOT\n"
            got: "FIRSTBOOT\n"

       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -NOT_FIRSTBOOT
       +FIRSTBOOT
       
     # ./spec/integration/build_spec.rb:179:in `expect_permanent_pxelinux_rendered_for_testnode01'
     # ./spec/integration/build_spec.rb:281:in `block (6 levels) in <top (required)>'
     # ./spec/integration/build_spec.rb:87:in `block in build_node'
     # ./spec/filesystem.rb:117:in `block in test'
     # ./spec/filesystem.rb:111:in `test'
     # ./spec/filesystem.rb:253:in `test'
     # ./spec/integration/build_spec.rb:74:in `build_node'
     # ./spec/integration/build_spec.rb:265:in `block (5 levels) in <top (required)>'
     # ./spec/spec_helper.rb:145:in `block (3 levels) in <top (required)>'
     # ./spec/filesystem.rb:117:in `block in test'
     # ./spec/filesystem.rb:111:in `test'
     # ./spec/spec_helper.rb:144:in `block (2 levels) in <top (required)>'

Top 2 slowest examples (12.45 seconds, 29.2% of total time):
  `metal build` for gender group interrupt handling exits on second interrupt
    6.32 seconds ./spec/integration/build_spec.rb:217
  `metal build` for gender group works
    6.14 seconds ./spec/integration/build_spec.rb:140

Top 2 slowest example groups:
  `metal build`
    4.98 seconds average (24.88 seconds / 5 examples) ./spec/integration/build_spec.rb:35
  Metalware::Status::Monitor
    1.98 seconds average (3.97 seconds / 2 examples) ./spec/slow/status/monitor_spec.rb:32

Finished in 42.64 seconds (files took 1.14 seconds to load)
389 examples, 1 failure, 3 pending

Failed examples:

rspec ./spec/integration/build_spec.rb:264 # `metal build` for gender group interrupt handling with mocked highline handles "no" to interrupt prompt

Randomized with seed 3341

Coverage report generated for RSpec to /tmp/metalware/coverage. 2915 / 3416 LOC (85.33%) covered.
```

**Comment by bobwhitelock** [comment] 2018-02-12 15:59
Is this a duplicate of https://github.com/alces-software/metalware/issues/293?

**Comment by WilliamMcCumstie** [comment] 2018-02-12 16:00
Similar but this is a different bug to those ones. It looks like there are a few

**Comment by bobwhitelock** [comment] 2018-02-12 16:04
Might as well keep these all in one issue anyway since they all seem to be intermittent failures with the same flaky test. Going to move this over there.

**Closed by bobwhitelock** 2018-02-12 16:04 UTC
Labels: bug, low priority
