### ISSUE TITLE
dev/binding branch: iteration error

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#171] opened 2017-08-22 09:32 UTC
When rendering a file (`metal render /tmp/test`) either for a node or with no argument there are errors with iterations. This has also been seen with `metal configure group nodes`. Trace outputs below.

```
[root@controller ~]# metal render /tmp/test node01 --trace
/opt/metalware/src/templating/iterable_recursive_open_struct.rb:37:in `each=': Cannot set property 'each', reserved to use for iteration (Metalware::IterableRecursiveOpenStructPropertyError)
When calling: firewall.each{ ... }
	from /opt/metalware/src/binding/parameter.rb:69:in `retrieve_config_value'
	from /opt/metalware/src/binding/parameter.rb:47:in `retrieve_value'
	from /opt/metalware/src/binding/wrapper.rb:67:in `alces_get_value'
	from /opt/metalware/src/binding/wrapper.rb:47:in `method_missing'
	from (erb):1:in `get_binding'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `eval'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `block in result'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:894:in `result'
	from /opt/metalware/src/templating/renderer.rb:44:in `replace_erb'
	from /opt/metalware/src/templater.rb:179:in `replace_erb'
	from /opt/metalware/src/templater.rb:165:in `block in render'
	from /opt/metalware/src/templater.rb:164:in `open'
	from /opt/metalware/src/templater.rb:164:in `render'
	from /opt/metalware/src/templater.rb:63:in `render'
	from /opt/metalware/src/templater.rb:67:in `render_to_stdout'
	from /opt/metalware/src/commands/render.rb:42:in `run'
	from /opt/metalware/src/command_helpers/base_command.rb:40:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
```

```
[root@controller repo]# metal configure group nodes
Genders host range specifier for this group, e.g. 'node01,node[05-08]' (1/13)
node0[1-5]
Additional genders groups for this group, e.g. 'gpunodes,nodes'; the group being configured is the primary group (2/13)  ||
cluster,domain
Kickstart template to use (3/13)  |default|

PXELINUX template to use (4/13)  |default|

Setup primary network (5/13) [yes/no]
yes
IP for nodes on the primary network (6/13)  |10.10.<%= alces.group_index %>.<%= alces.index %>|

Interface for the primary network (7/13)  |eth0|

Setup management network (8/13) [yes/no]
no
IP for nodes on the management network (9/13)  |10.11.<%= alces.group_index %>.<%= alces.index %>|

Interface for the management network (10/13)  |eth1|

Setup InfiniBand network (11/13) [yes/no]
yes
IP for nodes on the InfiniBand network (12/13)  |10.12.<%= alces.group_index %>.<%= alces.index %>|

Interface for the InfiniBand network (13/13)  |eth2|

/opt/metalware/src/templating/iterable_recursive_open_struct.rb:37:in `each=': Cannot set property 'each', reserved to use for iteration (Metalware::IterableRecursiveOpenStructPropertyError)
When calling: networks.each{ ... }
When calling: alces.groups{ ... }
	from /opt/metalware/src/binding/parameter.rb:69:in `retrieve_config_value'
	from /opt/metalware/src/binding/parameter.rb:47:in `retrieve_value'
	from /opt/metalware/src/binding/wrapper.rb:67:in `alces_get_value'
	from /opt/metalware/src/binding/wrapper.rb:47:in `method_missing'
	from (erb):4:in `block (2 levels) in get_binding'
	from /opt/metalware/src/templating/group_namespace.rb:48:in `block in nodes'
	from /opt/metalware/src/templating/group_namespace.rb:47:in `map'
	from /opt/metalware/src/templating/group_namespace.rb:47:in `nodes'
	from (erb):3:in `block in get_binding'
	from /opt/metalware/src/templating/magic_namespace.rb:87:in `block in groups'
	from /opt/metalware/src/group_cache.rb:55:in `block in each'
	from /opt/metalware/src/group_cache.rb:54:in `each'
	from /opt/metalware/src/group_cache.rb:54:in `each'
	from /opt/metalware/src/templating/magic_namespace.rb:86:in `map'
	from /opt/metalware/src/templating/magic_namespace.rb:86:in `groups'
	from /opt/metalware/src/binding/wrapper.rb:69:in `alces_get_value'
	from /opt/metalware/src/binding/wrapper.rb:47:in `method_missing'
	from (erb):2:in `get_binding'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `eval'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:893:in `block in result'
	from /opt/metalware/opt/ruby/lib/ruby/2.4.0/erb.rb:894:in `result'
	from /opt/metalware/src/templating/renderer.rb:44:in `replace_erb'
	from /opt/metalware/src/templater.rb:179:in `replace_erb'
	from /opt/metalware/src/templater.rb:165:in `block in render'
	from /opt/metalware/src/templater.rb:164:in `open'
	from /opt/metalware/src/templater.rb:164:in `render'
	from /opt/metalware/src/templater.rb:63:in `render'
	from /opt/metalware/src/templater.rb:97:in `render_managed_file'
	from /opt/metalware/src/domain_templates_renderer.rb:131:in `render_managed_section_template'
	from /opt/metalware/src/domain_templates_renderer.rb:127:in `render_hosts'
	from /opt/metalware/src/domain_templates_renderer.rb:38:in `block in render'
	from /opt/metalware/src/domain_templates_renderer.rb:37:in `each'
	from /opt/metalware/src/domain_templates_renderer.rb:37:in `render'
	from /opt/metalware/src/command_helpers/configure_command.rb:98:in `render_domain_templates'
	from /opt/metalware/src/command_helpers/configure_command.rb:45:in `run'
	from /opt/metalware/src/command_helpers/base_command.rb:40:in `initialize'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `new'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:217:in `call'
	from /opt/metalware/src/commander_extensions.rb:61:in `call'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/command.rb:184:in `run'
	from /opt/metalware/src/commander_extensions.rb:49:in `run'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:464:in `run_active_command'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/runner.rb:66:in `run!'
	from /opt/metalware/vendor/ruby/2.4.0/bundler/gems/commander-c99203ec5a74/lib/commander/delegates.rb:15:in `run!'
	from /opt/metalware/src/cli.rb:52:in `run!'
	from /opt/metalware/src/cli.rb:47:in `run'
	from bin/metal:28:in `<main>'
```

**Comment by WilliamMcCumstie** [comment] 2017-08-22 10:46
The bug was being caused by the new parameter binding. Previously it was treating `each` like a variable instead of a method with a block. Now if a block is provided, it will run the block instead.

Fixed in: da464a8fc5589a7afd3fac96147bcf5e1ad29550

**Closed by WilliamMcCumstie** 2017-08-22 10:46 UTC
Labels: bug
