### ISSUE TITLE
`alces.group_index` is not an integer

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/metalware#161] opened 2017-08-14 14:41 UTC
`alces.group_index` does not function the same way as `alces.index`. Take for example the following line from the domain config:
```
10.10.<%= alces.group_index %>.<%= alces.index + 1 %>
```
This will work absolutely fine, however if it is modified to:
```
10.10.<%= alces.group_index + 1 %>.<%= alces.index + 1 %>
```
Then the configure bombs out with the following error:
```
error: Attempted to call method `+` of unset template parameter. Use --trace to view backtrace
```
This issue can be fixed by setting the line to:
```
10.10.<%= alces.group_index.to_i + 1 %>.<%= alces.index + 1 %>
```

So, it seems that `alces.group_index` needs to be an integer so that the behaviour matches that of `alces.index`

**Comment by bobwhitelock** [comment] 2017-08-14 14:57
@ColonelPanicks: What are you rendering when this occurs?

If I create a template `foo.erb` containing the following:

```erb

<%= alces.group_index + 1  %>
```

then when rendered for a node this gives the following output:
```
[root@controller(dev) metalware]# bin/metal render foo.erb node01

1
```

However, when rendered for no node it gives the following:
```
[root@controller(dev) metalware]# bin/metal render foo.erb 
warning: Unset template parameter: nodename
warning: Unset template parameter: group_index
error: Attempted to call method `+` of unset template parameter. Use --trace to view backtrace
```

If you are seeing the same behaviour, i.e. you're getting this just when rendering not in a particular node context, then I believe the issue is that `group_index` is `nil` in this case, as what should the group index be when we don't have a group? I see 2 possible solutions to this:

1. Make where we use `alces.group_index` in templates robust to this not being set, i.e. robust when there is no group, e.g. by using something like this instead:

```erb
<%= (alces.group_index ? alces.group_index : 0) + 1 %>
```

2. Make `group_index` never be `nil`, by giving it a value even when we do not have a group because we are not in a node context. A reasonable value might be `0` in this case, but this could cause issues as we also use `0` for the first group configured; depending on how we use `group_index` there would be no way to distinguish these cases, which we may or may not care about.

**Comment by ColonelPanicks** [comment] 2017-08-14 15:22
@bobwhitelock thanks for clearing that up some more! To follow up:

- When would `group_index` be nil but still be used? Am I right in assuming that all nodes would have to be in a group anyway?

- When I applied the `to_i` fix I was able to generate `/etc/hosts` (by running through `metal configure domain`) and it only contains 5 nodes (`node0[1-5]`) which are all part of a group so where could `group_index` be slipping up during `configure` by rendering something containing `group_index` on no node?

I realise that both of the above are pretty similar questions! Just trying to get my head around it before deciding whether option 1 or 2 is better. Depending on when a `group_index` of nil would be used/valid will change how we go forward I think!

**Comment by ColonelPanicks** [comment] 2017-08-14 15:50
Following IRL conversation - `alces.group_index` will be modified to behave more like `alces.index` by defaulting to 0 instead of nil.

**Comment by WilliamMcCumstie** [comment] 2017-08-14 16:32
This sounds more like a bug in metalware due to a recent update than incorrect behaviour. The data structure used to return the `group_index` has recently changed which might be why you have a configured group without a group_index.

But beside this, we can't have an un-configured group return index 0 as it has already been taken. So the three options are:
1. raise and error if you try and access a non-existent group_index,
1. return a negative number as it shouldn't be used anyway,
1. return 0 BUT change the starting group index to 1. This way the first primary group will be index 1 and missing group_index's will be 0

**Comment by WilliamMcCumstie** [comment] 2017-08-14 18:47
As discussed in #162, the bug probably isn't caused by the change in the data structure, however it might be good to check this anyway.

We are going to implement option number 3. Please refer to the PR for more details.

**Closed** 2017-08-15 10:27 UTC
Labels: bug
